[workspace]
resolver = "2"

members = [
    "clarity",
    "web30"
]

[workspace.dependencies]
num256 = "0.5"

# used to resolve the recursive dep created by importing web30 as
# a dev dependency
[patch.crates-io]
clarity = { path = './clarity/' }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
incremental = false